# Generated by Django 5.2 on 2025-05-09 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('study_hours_per_day', models.FloatField()),
                ('social_media_hours', models.FloatField()),
                ('netflix_hours', models.FloatField()),
                ('part_time_job', models.IntegerField()),
                ('attendance_percentage', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('diet_quality', models.IntegerField()),
                ('exercise_frequency', models.IntegerField()),
                ('parental_education_level', models.IntegerField()),
                ('internet_quality', models.IntegerField()),
                ('mental_health_rating', models.IntegerField()),
                ('extracurricular_participation', models.IntegerField()),
                ('prediction_result', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='defeapp.accounts')),
            ],
        ),
    ]
